// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/metadatav1/metadata.proto

package metadatav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaType int32

const (
	MediaType_MEDIA_TYPE_UNSPECIFIED MediaType = 0
	MediaType_MEDIA_TYPE_MOVIE       MediaType = 1
	MediaType_MEDIA_TYPE_TV          MediaType = 2
)

// Enum value maps for MediaType.
var (
	MediaType_name = map[int32]string{
		0: "MEDIA_TYPE_UNSPECIFIED",
		1: "MEDIA_TYPE_MOVIE",
		2: "MEDIA_TYPE_TV",
	}
	MediaType_value = map[string]int32{
		"MEDIA_TYPE_UNSPECIFIED": 0,
		"MEDIA_TYPE_MOVIE":       1,
		"MEDIA_TYPE_TV":          2,
	}
)

func (x MediaType) Enum() *MediaType {
	p := new(MediaType)
	*p = x
	return p
}

func (x MediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_metadatav1_metadata_proto_enumTypes[0].Descriptor()
}

func (MediaType) Type() protoreflect.EnumType {
	return &file_proto_metadatav1_metadata_proto_enumTypes[0]
}

func (x MediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaType.Descriptor instead.
func (MediaType) EnumDescriptor() ([]byte, []int) {
	return file_proto_metadatav1_metadata_proto_rawDescGZIP(), []int{0}
}

type TrendingMediaType int32

const (
	TrendingMediaType_TRENDING_MEDIA_TYPE_UNSPECIFIED TrendingMediaType = 0
	TrendingMediaType_TRENDING_MEDIA_TYPE_ALL         TrendingMediaType = 1
	TrendingMediaType_TRENDING_MEDIA_TYPE_MOVIE       TrendingMediaType = 2
	TrendingMediaType_TRENDING_MEDIA_TYPE_TV          TrendingMediaType = 3
)

// Enum value maps for TrendingMediaType.
var (
	TrendingMediaType_name = map[int32]string{
		0: "TRENDING_MEDIA_TYPE_UNSPECIFIED",
		1: "TRENDING_MEDIA_TYPE_ALL",
		2: "TRENDING_MEDIA_TYPE_MOVIE",
		3: "TRENDING_MEDIA_TYPE_TV",
	}
	TrendingMediaType_value = map[string]int32{
		"TRENDING_MEDIA_TYPE_UNSPECIFIED": 0,
		"TRENDING_MEDIA_TYPE_ALL":         1,
		"TRENDING_MEDIA_TYPE_MOVIE":       2,
		"TRENDING_MEDIA_TYPE_TV":          3,
	}
)

func (x TrendingMediaType) Enum() *TrendingMediaType {
	p := new(TrendingMediaType)
	*p = x
	return p
}

func (x TrendingMediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrendingMediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_metadatav1_metadata_proto_enumTypes[1].Descriptor()
}

func (TrendingMediaType) Type() protoreflect.EnumType {
	return &file_proto_metadatav1_metadata_proto_enumTypes[1]
}

func (x TrendingMediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrendingMediaType.Descriptor instead.
func (TrendingMediaType) EnumDescriptor() ([]byte, []int) {
	return file_proto_metadatav1_metadata_proto_rawDescGZIP(), []int{1}
}

type TrendingTimeWindow int32

const (
	TrendingTimeWindow_TRENDING_TIME_WINDOW_UNSPECIFIED TrendingTimeWindow = 0
	TrendingTimeWindow_TRENDING_TIME_WINDOW_DAY         TrendingTimeWindow = 1
	TrendingTimeWindow_TRENDING_TIME_WINDOW_WEEK        TrendingTimeWindow = 2
)

// Enum value maps for TrendingTimeWindow.
var (
	TrendingTimeWindow_name = map[int32]string{
		0: "TRENDING_TIME_WINDOW_UNSPECIFIED",
		1: "TRENDING_TIME_WINDOW_DAY",
		2: "TRENDING_TIME_WINDOW_WEEK",
	}
	TrendingTimeWindow_value = map[string]int32{
		"TRENDING_TIME_WINDOW_UNSPECIFIED": 0,
		"TRENDING_TIME_WINDOW_DAY":         1,
		"TRENDING_TIME_WINDOW_WEEK":        2,
	}
)

func (x TrendingTimeWindow) Enum() *TrendingTimeWindow {
	p := new(TrendingTimeWindow)
	*p = x
	return p
}

func (x TrendingTimeWindow) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrendingTimeWindow) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_metadatav1_metadata_proto_enumTypes[2].Descriptor()
}

func (TrendingTimeWindow) Type() protoreflect.EnumType {
	return &file_proto_metadatav1_metadata_proto_enumTypes[2]
}

func (x TrendingTimeWindow) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrendingTimeWindow.Descriptor instead.
func (TrendingTimeWindow) EnumDescriptor() ([]byte, []int) {
	return file_proto_metadatav1_metadata_proto_rawDescGZIP(), []int{2}
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Type          MediaType              `protobuf:"varint,2,opt,name=type,proto3,enum=muxcore.metadata.v1.MediaType" json:"type,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_metadatav1_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetType() MediaType {
	if x != nil {
		return x.Type
	}
	return MediaType_MEDIA_TYPE_UNSPECIFIED
}

func (x *SearchRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	TotalResults  int32                  `protobuf:"varint,2,opt,name=total_results,json=totalResults,proto3" json:"total_results,omitempty"`
	TotalPages    int32                  `protobuf:"varint,3,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_metadatav1_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetTotalResults() int32 {
	if x != nil {
		return x.TotalResults
	}
	return 0
}

func (x *SearchResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *SearchResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type SearchResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	OriginalTitle    string                 `protobuf:"bytes,3,opt,name=original_title,json=originalTitle,proto3" json:"original_title,omitempty"`
	Overview         string                 `protobuf:"bytes,4,opt,name=overview,proto3" json:"overview,omitempty"`
	PosterPath       string                 `protobuf:"bytes,5,opt,name=poster_path,json=posterPath,proto3" json:"poster_path,omitempty"`
	BackdropPath     string                 `protobuf:"bytes,6,opt,name=backdrop_path,json=backdropPath,proto3" json:"backdrop_path,omitempty"`
	VoteAverage      float64                `protobuf:"fixed64,7,opt,name=vote_average,json=voteAverage,proto3" json:"vote_average,omitempty"`
	VoteCount        int32                  `protobuf:"varint,8,opt,name=vote_count,json=voteCount,proto3" json:"vote_count,omitempty"`
	ReleaseDate      string                 `protobuf:"bytes,9,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	MediaType        MediaType              `protobuf:"varint,10,opt,name=media_type,json=mediaType,proto3,enum=muxcore.metadata.v1.MediaType" json:"media_type,omitempty"`
	GenreIds         []int32                `protobuf:"varint,11,rep,packed,name=genre_ids,json=genreIds,proto3" json:"genre_ids,omitempty"`
	OriginalLanguage string                 `protobuf:"bytes,12,opt,name=original_language,json=originalLanguage,proto3" json:"original_language,omitempty"`
	Popularity       float64                `protobuf:"fixed64,13,opt,name=popularity,proto3" json:"popularity,omitempty"`
	Name             string                 `protobuf:"bytes,14,opt,name=name,proto3" json:"name,omitempty"`
	FirstAirDate     string                 `protobuf:"bytes,15,opt,name=first_air_date,json=firstAirDate,proto3" json:"first_air_date,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_proto_metadatav1_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResult) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SearchResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SearchResult) GetOriginalTitle() string {
	if x != nil {
		return x.OriginalTitle
	}
	return ""
}

func (x *SearchResult) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

func (x *SearchResult) GetPosterPath() string {
	if x != nil {
		return x.PosterPath
	}
	return ""
}

func (x *SearchResult) GetBackdropPath() string {
	if x != nil {
		return x.BackdropPath
	}
	return ""
}

func (x *SearchResult) GetVoteAverage() float64 {
	if x != nil {
		return x.VoteAverage
	}
	return 0
}

func (x *SearchResult) GetVoteCount() int32 {
	if x != nil {
		return x.VoteCount
	}
	return 0
}

func (x *SearchResult) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *SearchResult) GetMediaType() MediaType {
	if x != nil {
		return x.MediaType
	}
	return MediaType_MEDIA_TYPE_UNSPECIFIED
}

func (x *SearchResult) GetGenreIds() []int32 {
	if x != nil {
		return x.GenreIds
	}
	return nil
}

func (x *SearchResult) GetOriginalLanguage() string {
	if x != nil {
		return x.OriginalLanguage
	}
	return ""
}

func (x *SearchResult) GetPopularity() float64 {
	if x != nil {
		return x.Popularity
	}
	return 0
}

func (x *SearchResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchResult) GetFirstAirDate() string {
	if x != nil {
		return x.FirstAirDate
	}
	return ""
}

type GetMovieDetailsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TmdbId           int32                  `protobuf:"varint,1,opt,name=tmdb_id,json=tmdbId,proto3" json:"tmdb_id,omitempty"`
	Language         string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	AppendToResponse []string               `protobuf:"bytes,3,rep,name=append_to_response,json=appendToResponse,proto3" json:"append_to_response,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetMovieDetailsRequest) Reset() {
	*x = GetMovieDetailsRequest{}
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieDetailsRequest) ProtoMessage() {}

func (x *GetMovieDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetMovieDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_metadatav1_metadata_proto_rawDescGZIP(), []int{3}
}

func (x *GetMovieDetailsRequest) GetTmdbId() int32 {
	if x != nil {
		return x.TmdbId
	}
	return 0
}

func (x *GetMovieDetailsRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *GetMovieDetailsRequest) GetAppendToResponse() []string {
	if x != nil {
		return x.AppendToResponse
	}
	return nil
}

type GetMovieDetailsResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title               string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	OriginalTitle       string                 `protobuf:"bytes,3,opt,name=original_title,json=originalTitle,proto3" json:"original_title,omitempty"`
	Overview            string                 `protobuf:"bytes,4,opt,name=overview,proto3" json:"overview,omitempty"`
	Tagline             string                 `protobuf:"bytes,5,opt,name=tagline,proto3" json:"tagline,omitempty"`
	PosterPath          string                 `protobuf:"bytes,6,opt,name=poster_path,json=posterPath,proto3" json:"poster_path,omitempty"`
	BackdropPath        string                 `protobuf:"bytes,7,opt,name=backdrop_path,json=backdropPath,proto3" json:"backdrop_path,omitempty"`
	ReleaseDate         string                 `protobuf:"bytes,8,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	Runtime             int32                  `protobuf:"varint,9,opt,name=runtime,proto3" json:"runtime,omitempty"`
	VoteAverage         float64                `protobuf:"fixed64,10,opt,name=vote_average,json=voteAverage,proto3" json:"vote_average,omitempty"`
	VoteCount           int32                  `protobuf:"varint,11,opt,name=vote_count,json=voteCount,proto3" json:"vote_count,omitempty"`
	Popularity          float64                `protobuf:"fixed64,12,opt,name=popularity,proto3" json:"popularity,omitempty"`
	Status              string                 `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	OriginalLanguage    string                 `protobuf:"bytes,14,opt,name=original_language,json=originalLanguage,proto3" json:"original_language,omitempty"`
	Adult               bool                   `protobuf:"varint,15,opt,name=adult,proto3" json:"adult,omitempty"`
	Budget              int64                  `protobuf:"varint,16,opt,name=budget,proto3" json:"budget,omitempty"`
	Revenue             int64                  `protobuf:"varint,17,opt,name=revenue,proto3" json:"revenue,omitempty"`
	Homepage            string                 `protobuf:"bytes,18,opt,name=homepage,proto3" json:"homepage,omitempty"`
	ImdbId              string                 `protobuf:"bytes,19,opt,name=imdb_id,json=imdbId,proto3" json:"imdb_id,omitempty"`
	Genres              []*Genre               `protobuf:"bytes,20,rep,name=genres,proto3" json:"genres,omitempty"`
	ProductionCompanies []*ProductionCompany   `protobuf:"bytes,21,rep,name=production_companies,json=productionCompanies,proto3" json:"production_companies,omitempty"`
	SpokenLanguages     []*SpokenLanguage      `protobuf:"bytes,22,rep,name=spoken_languages,json=spokenLanguages,proto3" json:"spoken_languages,omitempty"`
	BackdropUrl         string                 `protobuf:"bytes,23,opt,name=backdrop_url,json=backdropUrl,proto3" json:"backdrop_url,omitempty"`
	PosterUrl           string                 `protobuf:"bytes,24,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`
	Videos              []*Video               `protobuf:"bytes,25,rep,name=videos,proto3" json:"videos,omitempty"`
	Credits             []*Credits             `protobuf:"bytes,26,rep,name=credits,proto3" json:"credits,omitempty"`
	BelongsToCollection *Collection            `protobuf:"bytes,27,opt,name=belongs_to_collection,json=belongsToCollection,proto3" json:"belongs_to_collection,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetMovieDetailsResponse) Reset() {
	*x = GetMovieDetailsResponse{}
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieDetailsResponse) ProtoMessage() {}

func (x *GetMovieDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetMovieDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_metadatav1_metadata_proto_rawDescGZIP(), []int{4}
}

func (x *GetMovieDetailsResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetMovieDetailsResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetMovieDetailsResponse) GetOriginalTitle() string {
	if x != nil {
		return x.OriginalTitle
	}
	return ""
}

func (x *GetMovieDetailsResponse) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

func (x *GetMovieDetailsResponse) GetTagline() string {
	if x != nil {
		return x.Tagline
	}
	return ""
}

func (x *GetMovieDetailsResponse) GetPosterPath() string {
	if x != nil {
		return x.PosterPath
	}
	return ""
}

func (x *GetMovieDetailsResponse) GetBackdropPath() string {
	if x != nil {
		return x.BackdropPath
	}
	return ""
}

func (x *GetMovieDetailsResponse) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *GetMovieDetailsResponse) GetRuntime() int32 {
	if x != nil {
		return x.Runtime
	}
	return 0
}

func (x *GetMovieDetailsResponse) GetVoteAverage() float64 {
	if x != nil {
		return x.VoteAverage
	}
	return 0
}

func (x *GetMovieDetailsResponse) GetVoteCount() int32 {
	if x != nil {
		return x.VoteCount
	}
	return 0
}

func (x *GetMovieDetailsResponse) GetPopularity() float64 {
	if x != nil {
		return x.Popularity
	}
	return 0
}

func (x *GetMovieDetailsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetMovieDetailsResponse) GetOriginalLanguage() string {
	if x != nil {
		return x.OriginalLanguage
	}
	return ""
}

func (x *GetMovieDetailsResponse) GetAdult() bool {
	if x != nil {
		return x.Adult
	}
	return false
}

func (x *GetMovieDetailsResponse) GetBudget() int64 {
	if x != nil {
		return x.Budget
	}
	return 0
}

func (x *GetMovieDetailsResponse) GetRevenue() int64 {
	if x != nil {
		return x.Revenue
	}
	return 0
}

func (x *GetMovieDetailsResponse) GetHomepage() string {
	if x != nil {
		return x.Homepage
	}
	return ""
}

func (x *GetMovieDetailsResponse) GetImdbId() string {
	if x != nil {
		return x.ImdbId
	}
	return ""
}

func (x *GetMovieDetailsResponse) GetGenres() []*Genre {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *GetMovieDetailsResponse) GetProductionCompanies() []*ProductionCompany {
	if x != nil {
		return x.ProductionCompanies
	}
	return nil
}

func (x *GetMovieDetailsResponse) GetSpokenLanguages() []*SpokenLanguage {
	if x != nil {
		return x.SpokenLanguages
	}
	return nil
}

func (x *GetMovieDetailsResponse) GetBackdropUrl() string {
	if x != nil {
		return x.BackdropUrl
	}
	return ""
}

func (x *GetMovieDetailsResponse) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *GetMovieDetailsResponse) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *GetMovieDetailsResponse) GetCredits() []*Credits {
	if x != nil {
		return x.Credits
	}
	return nil
}

func (x *GetMovieDetailsResponse) GetBelongsToCollection() *Collection {
	if x != nil {
		return x.BelongsToCollection
	}
	return nil
}

type Collection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PosterPath    string                 `protobuf:"bytes,3,opt,name=poster_path,json=posterPath,proto3" json:"poster_path,omitempty"`
	BackdropPath  string                 `protobuf:"bytes,4,opt,name=backdrop_path,json=backdropPath,proto3" json:"backdrop_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Collection) Reset() {
	*x = Collection{}
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Collection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collection) ProtoMessage() {}

func (x *Collection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collection.ProtoReflect.Descriptor instead.
func (*Collection) Descriptor() ([]byte, []int) {
	return file_proto_metadatav1_metadata_proto_rawDescGZIP(), []int{5}
}

func (x *Collection) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Collection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Collection) GetPosterPath() string {
	if x != nil {
		return x.PosterPath
	}
	return ""
}

func (x *Collection) GetBackdropPath() string {
	if x != nil {
		return x.BackdropPath
	}
	return ""
}

type Genre struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Genre) Reset() {
	*x = Genre{}
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Genre) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genre) ProtoMessage() {}

func (x *Genre) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genre.ProtoReflect.Descriptor instead.
func (*Genre) Descriptor() ([]byte, []int) {
	return file_proto_metadatav1_metadata_proto_rawDescGZIP(), []int{6}
}

func (x *Genre) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Genre) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProductionCompany struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LogoPath      string                 `protobuf:"bytes,3,opt,name=logo_path,json=logoPath,proto3" json:"logo_path,omitempty"`
	OriginCountry string                 `protobuf:"bytes,4,opt,name=origin_country,json=originCountry,proto3" json:"origin_country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductionCompany) Reset() {
	*x = ProductionCompany{}
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductionCompany) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductionCompany) ProtoMessage() {}

func (x *ProductionCompany) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductionCompany.ProtoReflect.Descriptor instead.
func (*ProductionCompany) Descriptor() ([]byte, []int) {
	return file_proto_metadatav1_metadata_proto_rawDescGZIP(), []int{7}
}

func (x *ProductionCompany) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductionCompany) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductionCompany) GetLogoPath() string {
	if x != nil {
		return x.LogoPath
	}
	return ""
}

func (x *ProductionCompany) GetOriginCountry() string {
	if x != nil {
		return x.OriginCountry
	}
	return ""
}

type SpokenLanguage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Iso_639_1     string                 `protobuf:"bytes,1,opt,name=iso_639_1,json=iso6391,proto3" json:"iso_639_1,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpokenLanguage) Reset() {
	*x = SpokenLanguage{}
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpokenLanguage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpokenLanguage) ProtoMessage() {}

func (x *SpokenLanguage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpokenLanguage.ProtoReflect.Descriptor instead.
func (*SpokenLanguage) Descriptor() ([]byte, []int) {
	return file_proto_metadatav1_metadata_proto_rawDescGZIP(), []int{8}
}

func (x *SpokenLanguage) GetIso_639_1() string {
	if x != nil {
		return x.Iso_639_1
	}
	return ""
}

func (x *SpokenLanguage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Video struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Site          string                 `protobuf:"bytes,4,opt,name=site,proto3" json:"site,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Video) Reset() {
	*x = Video{}
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_proto_metadatav1_metadata_proto_rawDescGZIP(), []int{9}
}

func (x *Video) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Video) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Video) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Video) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *Video) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Credits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cast          []*CastMember          `protobuf:"bytes,1,rep,name=cast,proto3" json:"cast,omitempty"`
	Crew          []*CrewMember          `protobuf:"bytes,2,rep,name=crew,proto3" json:"crew,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Credits) Reset() {
	*x = Credits{}
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credits) ProtoMessage() {}

func (x *Credits) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Credits.ProtoReflect.Descriptor instead.
func (*Credits) Descriptor() ([]byte, []int) {
	return file_proto_metadatav1_metadata_proto_rawDescGZIP(), []int{10}
}

func (x *Credits) GetCast() []*CastMember {
	if x != nil {
		return x.Cast
	}
	return nil
}

func (x *Credits) GetCrew() []*CrewMember {
	if x != nil {
		return x.Crew
	}
	return nil
}

type CastMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Character     string                 `protobuf:"bytes,3,opt,name=character,proto3" json:"character,omitempty"`
	ProfilePath   string                 `protobuf:"bytes,4,opt,name=profile_path,json=profilePath,proto3" json:"profile_path,omitempty"`
	Order         int32                  `protobuf:"varint,5,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CastMember) Reset() {
	*x = CastMember{}
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CastMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastMember) ProtoMessage() {}

func (x *CastMember) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastMember.ProtoReflect.Descriptor instead.
func (*CastMember) Descriptor() ([]byte, []int) {
	return file_proto_metadatav1_metadata_proto_rawDescGZIP(), []int{11}
}

func (x *CastMember) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CastMember) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CastMember) GetCharacter() string {
	if x != nil {
		return x.Character
	}
	return ""
}

func (x *CastMember) GetProfilePath() string {
	if x != nil {
		return x.ProfilePath
	}
	return ""
}

func (x *CastMember) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type CrewMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Job           string                 `protobuf:"bytes,3,opt,name=job,proto3" json:"job,omitempty"`
	Department    string                 `protobuf:"bytes,4,opt,name=department,proto3" json:"department,omitempty"`
	ProfilePath   string                 `protobuf:"bytes,5,opt,name=profile_path,json=profilePath,proto3" json:"profile_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrewMember) Reset() {
	*x = CrewMember{}
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrewMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrewMember) ProtoMessage() {}

func (x *CrewMember) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrewMember.ProtoReflect.Descriptor instead.
func (*CrewMember) Descriptor() ([]byte, []int) {
	return file_proto_metadatav1_metadata_proto_rawDescGZIP(), []int{12}
}

func (x *CrewMember) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CrewMember) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CrewMember) GetJob() string {
	if x != nil {
		return x.Job
	}
	return ""
}

func (x *CrewMember) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *CrewMember) GetProfilePath() string {
	if x != nil {
		return x.ProfilePath
	}
	return ""
}

type GetTVDetailsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TmdbId           int32                  `protobuf:"varint,1,opt,name=tmdb_id,json=tmdbId,proto3" json:"tmdb_id,omitempty"`
	Language         string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	AppendToResponse []string               `protobuf:"bytes,3,rep,name=append_to_response,json=appendToResponse,proto3" json:"append_to_response,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetTVDetailsRequest) Reset() {
	*x = GetTVDetailsRequest{}
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTVDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTVDetailsRequest) ProtoMessage() {}

func (x *GetTVDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTVDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetTVDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_metadatav1_metadata_proto_rawDescGZIP(), []int{13}
}

func (x *GetTVDetailsRequest) GetTmdbId() int32 {
	if x != nil {
		return x.TmdbId
	}
	return 0
}

func (x *GetTVDetailsRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *GetTVDetailsRequest) GetAppendToResponse() []string {
	if x != nil {
		return x.AppendToResponse
	}
	return nil
}

type GetTVDetailsResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OriginalName        string                 `protobuf:"bytes,3,opt,name=original_name,json=originalName,proto3" json:"original_name,omitempty"`
	Overview            string                 `protobuf:"bytes,4,opt,name=overview,proto3" json:"overview,omitempty"`
	Tagline             string                 `protobuf:"bytes,5,opt,name=tagline,proto3" json:"tagline,omitempty"`
	PosterPath          string                 `protobuf:"bytes,6,opt,name=poster_path,json=posterPath,proto3" json:"poster_path,omitempty"`
	BackdropPath        string                 `protobuf:"bytes,7,opt,name=backdrop_path,json=backdropPath,proto3" json:"backdrop_path,omitempty"`
	FirstAirDate        string                 `protobuf:"bytes,8,opt,name=first_air_date,json=firstAirDate,proto3" json:"first_air_date,omitempty"`
	LastAirDate         string                 `protobuf:"bytes,9,opt,name=last_air_date,json=lastAirDate,proto3" json:"last_air_date,omitempty"`
	NumberOfSeasons     int32                  `protobuf:"varint,10,opt,name=number_of_seasons,json=numberOfSeasons,proto3" json:"number_of_seasons,omitempty"`
	NumberOfEpisodes    int32                  `protobuf:"varint,11,opt,name=number_of_episodes,json=numberOfEpisodes,proto3" json:"number_of_episodes,omitempty"`
	VoteAverage         float64                `protobuf:"fixed64,12,opt,name=vote_average,json=voteAverage,proto3" json:"vote_average,omitempty"`
	VoteCount           int32                  `protobuf:"varint,13,opt,name=vote_count,json=voteCount,proto3" json:"vote_count,omitempty"`
	Popularity          float64                `protobuf:"fixed64,14,opt,name=popularity,proto3" json:"popularity,omitempty"`
	Status              string                 `protobuf:"bytes,15,opt,name=status,proto3" json:"status,omitempty"`
	OriginalLanguage    string                 `protobuf:"bytes,16,opt,name=original_language,json=originalLanguage,proto3" json:"original_language,omitempty"`
	Homepage            string                 `protobuf:"bytes,17,opt,name=homepage,proto3" json:"homepage,omitempty"`
	InProduction        string                 `protobuf:"bytes,18,opt,name=in_production,json=inProduction,proto3" json:"in_production,omitempty"`
	Genres              []*Genre               `protobuf:"bytes,19,rep,name=genres,proto3" json:"genres,omitempty"`
	Seasons             []*Season              `protobuf:"bytes,20,rep,name=seasons,proto3" json:"seasons,omitempty"`
	ProductionCompanies []*ProductionCompany   `protobuf:"bytes,21,rep,name=production_companies,json=productionCompanies,proto3" json:"production_companies,omitempty"`
	SpokenLanguages     []*SpokenLanguage      `protobuf:"bytes,22,rep,name=spoken_languages,json=spokenLanguages,proto3" json:"spoken_languages,omitempty"`
	BackdropUrl         string                 `protobuf:"bytes,23,opt,name=backdrop_url,json=backdropUrl,proto3" json:"backdrop_url,omitempty"`
	PosterUrl           string                 `protobuf:"bytes,24,opt,name=poster_url,json=posterUrl,proto3" json:"poster_url,omitempty"`
	Videos              []*Video               `protobuf:"bytes,25,rep,name=videos,proto3" json:"videos,omitempty"`
	Credits             []*Credits             `protobuf:"bytes,26,rep,name=credits,proto3" json:"credits,omitempty"`
	CreatedBy           []*CreatedBy           `protobuf:"bytes,27,rep,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Networks            []*Network             `protobuf:"bytes,28,rep,name=networks,proto3" json:"networks,omitempty"`
	OriginCountry       []string               `protobuf:"bytes,29,rep,name=origin_country,json=originCountry,proto3" json:"origin_country,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetTVDetailsResponse) Reset() {
	*x = GetTVDetailsResponse{}
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTVDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTVDetailsResponse) ProtoMessage() {}

func (x *GetTVDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTVDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetTVDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_metadatav1_metadata_proto_rawDescGZIP(), []int{14}
}

func (x *GetTVDetailsResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetTVDetailsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTVDetailsResponse) GetOriginalName() string {
	if x != nil {
		return x.OriginalName
	}
	return ""
}

func (x *GetTVDetailsResponse) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

func (x *GetTVDetailsResponse) GetTagline() string {
	if x != nil {
		return x.Tagline
	}
	return ""
}

func (x *GetTVDetailsResponse) GetPosterPath() string {
	if x != nil {
		return x.PosterPath
	}
	return ""
}

func (x *GetTVDetailsResponse) GetBackdropPath() string {
	if x != nil {
		return x.BackdropPath
	}
	return ""
}

func (x *GetTVDetailsResponse) GetFirstAirDate() string {
	if x != nil {
		return x.FirstAirDate
	}
	return ""
}

func (x *GetTVDetailsResponse) GetLastAirDate() string {
	if x != nil {
		return x.LastAirDate
	}
	return ""
}

func (x *GetTVDetailsResponse) GetNumberOfSeasons() int32 {
	if x != nil {
		return x.NumberOfSeasons
	}
	return 0
}

func (x *GetTVDetailsResponse) GetNumberOfEpisodes() int32 {
	if x != nil {
		return x.NumberOfEpisodes
	}
	return 0
}

func (x *GetTVDetailsResponse) GetVoteAverage() float64 {
	if x != nil {
		return x.VoteAverage
	}
	return 0
}

func (x *GetTVDetailsResponse) GetVoteCount() int32 {
	if x != nil {
		return x.VoteCount
	}
	return 0
}

func (x *GetTVDetailsResponse) GetPopularity() float64 {
	if x != nil {
		return x.Popularity
	}
	return 0
}

func (x *GetTVDetailsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetTVDetailsResponse) GetOriginalLanguage() string {
	if x != nil {
		return x.OriginalLanguage
	}
	return ""
}

func (x *GetTVDetailsResponse) GetHomepage() string {
	if x != nil {
		return x.Homepage
	}
	return ""
}

func (x *GetTVDetailsResponse) GetInProduction() string {
	if x != nil {
		return x.InProduction
	}
	return ""
}

func (x *GetTVDetailsResponse) GetGenres() []*Genre {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *GetTVDetailsResponse) GetSeasons() []*Season {
	if x != nil {
		return x.Seasons
	}
	return nil
}

func (x *GetTVDetailsResponse) GetProductionCompanies() []*ProductionCompany {
	if x != nil {
		return x.ProductionCompanies
	}
	return nil
}

func (x *GetTVDetailsResponse) GetSpokenLanguages() []*SpokenLanguage {
	if x != nil {
		return x.SpokenLanguages
	}
	return nil
}

func (x *GetTVDetailsResponse) GetBackdropUrl() string {
	if x != nil {
		return x.BackdropUrl
	}
	return ""
}

func (x *GetTVDetailsResponse) GetPosterUrl() string {
	if x != nil {
		return x.PosterUrl
	}
	return ""
}

func (x *GetTVDetailsResponse) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *GetTVDetailsResponse) GetCredits() []*Credits {
	if x != nil {
		return x.Credits
	}
	return nil
}

func (x *GetTVDetailsResponse) GetCreatedBy() []*CreatedBy {
	if x != nil {
		return x.CreatedBy
	}
	return nil
}

func (x *GetTVDetailsResponse) GetNetworks() []*Network {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *GetTVDetailsResponse) GetOriginCountry() []string {
	if x != nil {
		return x.OriginCountry
	}
	return nil
}

type CreatedBy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProfilePath   string                 `protobuf:"bytes,3,opt,name=profile_path,json=profilePath,proto3" json:"profile_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatedBy) Reset() {
	*x = CreatedBy{}
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatedBy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatedBy) ProtoMessage() {}

func (x *CreatedBy) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatedBy.ProtoReflect.Descriptor instead.
func (*CreatedBy) Descriptor() ([]byte, []int) {
	return file_proto_metadatav1_metadata_proto_rawDescGZIP(), []int{15}
}

func (x *CreatedBy) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreatedBy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatedBy) GetProfilePath() string {
	if x != nil {
		return x.ProfilePath
	}
	return ""
}

type Network struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LogoPath      string                 `protobuf:"bytes,3,opt,name=logo_path,json=logoPath,proto3" json:"logo_path,omitempty"`
	OriginCountry string                 `protobuf:"bytes,4,opt,name=origin_country,json=originCountry,proto3" json:"origin_country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Network) Reset() {
	*x = Network{}
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network) ProtoMessage() {}

func (x *Network) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network.ProtoReflect.Descriptor instead.
func (*Network) Descriptor() ([]byte, []int) {
	return file_proto_metadatav1_metadata_proto_rawDescGZIP(), []int{16}
}

func (x *Network) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Network) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Network) GetLogoPath() string {
	if x != nil {
		return x.LogoPath
	}
	return ""
}

func (x *Network) GetOriginCountry() string {
	if x != nil {
		return x.OriginCountry
	}
	return ""
}

type Season struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Overview      string                 `protobuf:"bytes,3,opt,name=overview,proto3" json:"overview,omitempty"`
	PosterPath    string                 `protobuf:"bytes,4,opt,name=poster_path,json=posterPath,proto3" json:"poster_path,omitempty"`
	AirDate       string                 `protobuf:"bytes,5,opt,name=air_date,json=airDate,proto3" json:"air_date,omitempty"`
	SeasonNumber  int32                  `protobuf:"varint,6,opt,name=season_number,json=seasonNumber,proto3" json:"season_number,omitempty"`
	EpisodeCount  int32                  `protobuf:"varint,7,opt,name=episode_count,json=episodeCount,proto3" json:"episode_count,omitempty"`
	VoteAverage   float64                `protobuf:"fixed64,8,opt,name=vote_average,json=voteAverage,proto3" json:"vote_average,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Season) Reset() {
	*x = Season{}
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Season) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Season) ProtoMessage() {}

func (x *Season) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Season.ProtoReflect.Descriptor instead.
func (*Season) Descriptor() ([]byte, []int) {
	return file_proto_metadatav1_metadata_proto_rawDescGZIP(), []int{17}
}

func (x *Season) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Season) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Season) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

func (x *Season) GetPosterPath() string {
	if x != nil {
		return x.PosterPath
	}
	return ""
}

func (x *Season) GetAirDate() string {
	if x != nil {
		return x.AirDate
	}
	return ""
}

func (x *Season) GetSeasonNumber() int32 {
	if x != nil {
		return x.SeasonNumber
	}
	return 0
}

func (x *Season) GetEpisodeCount() int32 {
	if x != nil {
		return x.EpisodeCount
	}
	return 0
}

func (x *Season) GetVoteAverage() float64 {
	if x != nil {
		return x.VoteAverage
	}
	return 0
}

type GetConfigurationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigurationRequest) Reset() {
	*x = GetConfigurationRequest{}
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigurationRequest) ProtoMessage() {}

func (x *GetConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigurationRequest.ProtoReflect.Descriptor instead.
func (*GetConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_proto_metadatav1_metadata_proto_rawDescGZIP(), []int{18}
}

type GetConfigurationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseUrl       string                 `protobuf:"bytes,1,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	PosterSizes   []string               `protobuf:"bytes,2,rep,name=poster_sizes,json=posterSizes,proto3" json:"poster_sizes,omitempty"`
	BackdropSizes []string               `protobuf:"bytes,3,rep,name=backdrop_sizes,json=backdropSizes,proto3" json:"backdrop_sizes,omitempty"`
	LogoSizes     []string               `protobuf:"bytes,4,rep,name=logo_sizes,json=logoSizes,proto3" json:"logo_sizes,omitempty"`
	ProfileSizes  []string               `protobuf:"bytes,5,rep,name=profile_sizes,json=profileSizes,proto3" json:"profile_sizes,omitempty"`
	StillSizes    []string               `protobuf:"bytes,6,rep,name=still_sizes,json=stillSizes,proto3" json:"still_sizes,omitempty"`
	SecureBaseUrl string                 `protobuf:"bytes,7,opt,name=secure_base_url,json=secureBaseUrl,proto3" json:"secure_base_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigurationResponse) Reset() {
	*x = GetConfigurationResponse{}
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigurationResponse) ProtoMessage() {}

func (x *GetConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigurationResponse.ProtoReflect.Descriptor instead.
func (*GetConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_proto_metadatav1_metadata_proto_rawDescGZIP(), []int{19}
}

func (x *GetConfigurationResponse) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *GetConfigurationResponse) GetPosterSizes() []string {
	if x != nil {
		return x.PosterSizes
	}
	return nil
}

func (x *GetConfigurationResponse) GetBackdropSizes() []string {
	if x != nil {
		return x.BackdropSizes
	}
	return nil
}

func (x *GetConfigurationResponse) GetLogoSizes() []string {
	if x != nil {
		return x.LogoSizes
	}
	return nil
}

func (x *GetConfigurationResponse) GetProfileSizes() []string {
	if x != nil {
		return x.ProfileSizes
	}
	return nil
}

func (x *GetConfigurationResponse) GetStillSizes() []string {
	if x != nil {
		return x.StillSizes
	}
	return nil
}

func (x *GetConfigurationResponse) GetSecureBaseUrl() string {
	if x != nil {
		return x.SecureBaseUrl
	}
	return ""
}

type ListTrendingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaType     TrendingMediaType      `protobuf:"varint,1,opt,name=media_type,json=mediaType,proto3,enum=muxcore.metadata.v1.TrendingMediaType" json:"media_type,omitempty"`
	TimeWindow    TrendingTimeWindow     `protobuf:"varint,2,opt,name=time_window,json=timeWindow,proto3,enum=muxcore.metadata.v1.TrendingTimeWindow" json:"time_window,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTrendingRequest) Reset() {
	*x = ListTrendingRequest{}
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrendingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrendingRequest) ProtoMessage() {}

func (x *ListTrendingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrendingRequest.ProtoReflect.Descriptor instead.
func (*ListTrendingRequest) Descriptor() ([]byte, []int) {
	return file_proto_metadatav1_metadata_proto_rawDescGZIP(), []int{20}
}

func (x *ListTrendingRequest) GetMediaType() TrendingMediaType {
	if x != nil {
		return x.MediaType
	}
	return TrendingMediaType_TRENDING_MEDIA_TYPE_UNSPECIFIED
}

func (x *ListTrendingRequest) GetTimeWindow() TrendingTimeWindow {
	if x != nil {
		return x.TimeWindow
	}
	return TrendingTimeWindow_TRENDING_TIME_WINDOW_UNSPECIFIED
}

func (x *ListTrendingRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTrendingRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type ListTrendingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	TotalResults  int32                  `protobuf:"varint,2,opt,name=total_results,json=totalResults,proto3" json:"total_results,omitempty"`
	TotalPages    int32                  `protobuf:"varint,3,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTrendingResponse) Reset() {
	*x = ListTrendingResponse{}
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrendingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrendingResponse) ProtoMessage() {}

func (x *ListTrendingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrendingResponse.ProtoReflect.Descriptor instead.
func (*ListTrendingResponse) Descriptor() ([]byte, []int) {
	return file_proto_metadatav1_metadata_proto_rawDescGZIP(), []int{21}
}

func (x *ListTrendingResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ListTrendingResponse) GetTotalResults() int32 {
	if x != nil {
		return x.TotalResults
	}
	return 0
}

func (x *ListTrendingResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *ListTrendingResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type ListPopularRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MediaType              `protobuf:"varint,1,opt,name=type,proto3,enum=muxcore.metadata.v1.MediaType" json:"type,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPopularRequest) Reset() {
	*x = ListPopularRequest{}
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPopularRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPopularRequest) ProtoMessage() {}

func (x *ListPopularRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPopularRequest.ProtoReflect.Descriptor instead.
func (*ListPopularRequest) Descriptor() ([]byte, []int) {
	return file_proto_metadatav1_metadata_proto_rawDescGZIP(), []int{22}
}

func (x *ListPopularRequest) GetType() MediaType {
	if x != nil {
		return x.Type
	}
	return MediaType_MEDIA_TYPE_UNSPECIFIED
}

func (x *ListPopularRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPopularRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type ListPopularResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	TotalResults  int32                  `protobuf:"varint,2,opt,name=total_results,json=totalResults,proto3" json:"total_results,omitempty"`
	TotalPages    int32                  `protobuf:"varint,3,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPopularResponse) Reset() {
	*x = ListPopularResponse{}
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPopularResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPopularResponse) ProtoMessage() {}

func (x *ListPopularResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadatav1_metadata_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPopularResponse.ProtoReflect.Descriptor instead.
func (*ListPopularResponse) Descriptor() ([]byte, []int) {
	return file_proto_metadatav1_metadata_proto_rawDescGZIP(), []int{23}
}

func (x *ListPopularResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ListPopularResponse) GetTotalResults() int32 {
	if x != nil {
		return x.TotalResults
	}
	return 0
}

func (x *ListPopularResponse) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *ListPopularResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

var File_proto_metadatav1_metadata_proto protoreflect.FileDescriptor

const file_proto_metadatav1_metadata_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/metadatav1/metadata.proto\x12\x13muxcore.metadata.v1\"\x89\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x122\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1e.muxcore.metadata.v1.MediaTypeR\x04type\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\"\xa7\x01\n" +
	"\x0eSearchResponse\x12;\n" +
	"\aresults\x18\x01 \x03(\v2!.muxcore.metadata.v1.SearchResultR\aresults\x12#\n" +
	"\rtotal_results\x18\x02 \x01(\x05R\ftotalResults\x12\x1f\n" +
	"\vtotal_pages\x18\x03 \x01(\x05R\n" +
	"totalPages\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\"\x85\x04\n" +
	"\fSearchResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\x0eoriginal_title\x18\x03 \x01(\tR\roriginalTitle\x12\x1a\n" +
	"\boverview\x18\x04 \x01(\tR\boverview\x12\x1f\n" +
	"\vposter_path\x18\x05 \x01(\tR\n" +
	"posterPath\x12#\n" +
	"\rbackdrop_path\x18\x06 \x01(\tR\fbackdropPath\x12!\n" +
	"\fvote_average\x18\a \x01(\x01R\vvoteAverage\x12\x1d\n" +
	"\n" +
	"vote_count\x18\b \x01(\x05R\tvoteCount\x12!\n" +
	"\frelease_date\x18\t \x01(\tR\vreleaseDate\x12=\n" +
	"\n" +
	"media_type\x18\n" +
	" \x01(\x0e2\x1e.muxcore.metadata.v1.MediaTypeR\tmediaType\x12\x1b\n" +
	"\tgenre_ids\x18\v \x03(\x05R\bgenreIds\x12+\n" +
	"\x11original_language\x18\f \x01(\tR\x10originalLanguage\x12\x1e\n" +
	"\n" +
	"popularity\x18\r \x01(\x01R\n" +
	"popularity\x12\x12\n" +
	"\x04name\x18\x0e \x01(\tR\x04name\x12$\n" +
	"\x0efirst_air_date\x18\x0f \x01(\tR\ffirstAirDate\"{\n" +
	"\x16GetMovieDetailsRequest\x12\x17\n" +
	"\atmdb_id\x18\x01 \x01(\x05R\x06tmdbId\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12,\n" +
	"\x12append_to_response\x18\x03 \x03(\tR\x10appendToResponse\"\xa5\b\n" +
	"\x17GetMovieDetailsResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12%\n" +
	"\x0eoriginal_title\x18\x03 \x01(\tR\roriginalTitle\x12\x1a\n" +
	"\boverview\x18\x04 \x01(\tR\boverview\x12\x18\n" +
	"\atagline\x18\x05 \x01(\tR\atagline\x12\x1f\n" +
	"\vposter_path\x18\x06 \x01(\tR\n" +
	"posterPath\x12#\n" +
	"\rbackdrop_path\x18\a \x01(\tR\fbackdropPath\x12!\n" +
	"\frelease_date\x18\b \x01(\tR\vreleaseDate\x12\x18\n" +
	"\aruntime\x18\t \x01(\x05R\aruntime\x12!\n" +
	"\fvote_average\x18\n" +
	" \x01(\x01R\vvoteAverage\x12\x1d\n" +
	"\n" +
	"vote_count\x18\v \x01(\x05R\tvoteCount\x12\x1e\n" +
	"\n" +
	"popularity\x18\f \x01(\x01R\n" +
	"popularity\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status\x12+\n" +
	"\x11original_language\x18\x0e \x01(\tR\x10originalLanguage\x12\x14\n" +
	"\x05adult\x18\x0f \x01(\bR\x05adult\x12\x16\n" +
	"\x06budget\x18\x10 \x01(\x03R\x06budget\x12\x18\n" +
	"\arevenue\x18\x11 \x01(\x03R\arevenue\x12\x1a\n" +
	"\bhomepage\x18\x12 \x01(\tR\bhomepage\x12\x17\n" +
	"\aimdb_id\x18\x13 \x01(\tR\x06imdbId\x122\n" +
	"\x06genres\x18\x14 \x03(\v2\x1a.muxcore.metadata.v1.GenreR\x06genres\x12Y\n" +
	"\x14production_companies\x18\x15 \x03(\v2&.muxcore.metadata.v1.ProductionCompanyR\x13productionCompanies\x12N\n" +
	"\x10spoken_languages\x18\x16 \x03(\v2#.muxcore.metadata.v1.SpokenLanguageR\x0fspokenLanguages\x12!\n" +
	"\fbackdrop_url\x18\x17 \x01(\tR\vbackdropUrl\x12\x1d\n" +
	"\n" +
	"poster_url\x18\x18 \x01(\tR\tposterUrl\x122\n" +
	"\x06videos\x18\x19 \x03(\v2\x1a.muxcore.metadata.v1.VideoR\x06videos\x126\n" +
	"\acredits\x18\x1a \x03(\v2\x1c.muxcore.metadata.v1.CreditsR\acredits\x12S\n" +
	"\x15belongs_to_collection\x18\x1b \x01(\v2\x1f.muxcore.metadata.v1.CollectionR\x13belongsToCollection\"v\n" +
	"\n" +
	"Collection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vposter_path\x18\x03 \x01(\tR\n" +
	"posterPath\x12#\n" +
	"\rbackdrop_path\x18\x04 \x01(\tR\fbackdropPath\"+\n" +
	"\x05Genre\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"{\n" +
	"\x11ProductionCompany\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tlogo_path\x18\x03 \x01(\tR\blogoPath\x12%\n" +
	"\x0eorigin_country\x18\x04 \x01(\tR\roriginCountry\"@\n" +
	"\x0eSpokenLanguage\x12\x1a\n" +
	"\tiso_639_1\x18\x01 \x01(\tR\aiso6391\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"e\n" +
	"\x05Video\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04site\x18\x04 \x01(\tR\x04site\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\"s\n" +
	"\aCredits\x123\n" +
	"\x04cast\x18\x01 \x03(\v2\x1f.muxcore.metadata.v1.CastMemberR\x04cast\x123\n" +
	"\x04crew\x18\x02 \x03(\v2\x1f.muxcore.metadata.v1.CrewMemberR\x04crew\"\x87\x01\n" +
	"\n" +
	"CastMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tcharacter\x18\x03 \x01(\tR\tcharacter\x12!\n" +
	"\fprofile_path\x18\x04 \x01(\tR\vprofilePath\x12\x14\n" +
	"\x05order\x18\x05 \x01(\x05R\x05order\"\x85\x01\n" +
	"\n" +
	"CrewMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03job\x18\x03 \x01(\tR\x03job\x12\x1e\n" +
	"\n" +
	"department\x18\x04 \x01(\tR\n" +
	"department\x12!\n" +
	"\fprofile_path\x18\x05 \x01(\tR\vprofilePath\"x\n" +
	"\x13GetTVDetailsRequest\x12\x17\n" +
	"\atmdb_id\x18\x01 \x01(\x05R\x06tmdbId\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12,\n" +
	"\x12append_to_response\x18\x03 \x03(\tR\x10appendToResponse\"\xcb\t\n" +
	"\x14GetTVDetailsResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\roriginal_name\x18\x03 \x01(\tR\foriginalName\x12\x1a\n" +
	"\boverview\x18\x04 \x01(\tR\boverview\x12\x18\n" +
	"\atagline\x18\x05 \x01(\tR\atagline\x12\x1f\n" +
	"\vposter_path\x18\x06 \x01(\tR\n" +
	"posterPath\x12#\n" +
	"\rbackdrop_path\x18\a \x01(\tR\fbackdropPath\x12$\n" +
	"\x0efirst_air_date\x18\b \x01(\tR\ffirstAirDate\x12\"\n" +
	"\rlast_air_date\x18\t \x01(\tR\vlastAirDate\x12*\n" +
	"\x11number_of_seasons\x18\n" +
	" \x01(\x05R\x0fnumberOfSeasons\x12,\n" +
	"\x12number_of_episodes\x18\v \x01(\x05R\x10numberOfEpisodes\x12!\n" +
	"\fvote_average\x18\f \x01(\x01R\vvoteAverage\x12\x1d\n" +
	"\n" +
	"vote_count\x18\r \x01(\x05R\tvoteCount\x12\x1e\n" +
	"\n" +
	"popularity\x18\x0e \x01(\x01R\n" +
	"popularity\x12\x16\n" +
	"\x06status\x18\x0f \x01(\tR\x06status\x12+\n" +
	"\x11original_language\x18\x10 \x01(\tR\x10originalLanguage\x12\x1a\n" +
	"\bhomepage\x18\x11 \x01(\tR\bhomepage\x12#\n" +
	"\rin_production\x18\x12 \x01(\tR\finProduction\x122\n" +
	"\x06genres\x18\x13 \x03(\v2\x1a.muxcore.metadata.v1.GenreR\x06genres\x125\n" +
	"\aseasons\x18\x14 \x03(\v2\x1b.muxcore.metadata.v1.SeasonR\aseasons\x12Y\n" +
	"\x14production_companies\x18\x15 \x03(\v2&.muxcore.metadata.v1.ProductionCompanyR\x13productionCompanies\x12N\n" +
	"\x10spoken_languages\x18\x16 \x03(\v2#.muxcore.metadata.v1.SpokenLanguageR\x0fspokenLanguages\x12!\n" +
	"\fbackdrop_url\x18\x17 \x01(\tR\vbackdropUrl\x12\x1d\n" +
	"\n" +
	"poster_url\x18\x18 \x01(\tR\tposterUrl\x122\n" +
	"\x06videos\x18\x19 \x03(\v2\x1a.muxcore.metadata.v1.VideoR\x06videos\x126\n" +
	"\acredits\x18\x1a \x03(\v2\x1c.muxcore.metadata.v1.CreditsR\acredits\x12=\n" +
	"\n" +
	"created_by\x18\x1b \x03(\v2\x1e.muxcore.metadata.v1.CreatedByR\tcreatedBy\x128\n" +
	"\bnetworks\x18\x1c \x03(\v2\x1c.muxcore.metadata.v1.NetworkR\bnetworks\x12%\n" +
	"\x0eorigin_country\x18\x1d \x03(\tR\roriginCountry\"R\n" +
	"\tCreatedBy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fprofile_path\x18\x03 \x01(\tR\vprofilePath\"q\n" +
	"\aNetwork\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tlogo_path\x18\x03 \x01(\tR\blogoPath\x12%\n" +
	"\x0eorigin_country\x18\x04 \x01(\tR\roriginCountry\"\xf1\x01\n" +
	"\x06Season\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\boverview\x18\x03 \x01(\tR\boverview\x12\x1f\n" +
	"\vposter_path\x18\x04 \x01(\tR\n" +
	"posterPath\x12\x19\n" +
	"\bair_date\x18\x05 \x01(\tR\aairDate\x12#\n" +
	"\rseason_number\x18\x06 \x01(\x05R\fseasonNumber\x12#\n" +
	"\repisode_count\x18\a \x01(\x05R\fepisodeCount\x12!\n" +
	"\fvote_average\x18\b \x01(\x01R\vvoteAverage\"\x19\n" +
	"\x17GetConfigurationRequest\"\x8c\x02\n" +
	"\x18GetConfigurationResponse\x12\x19\n" +
	"\bbase_url\x18\x01 \x01(\tR\abaseUrl\x12!\n" +
	"\fposter_sizes\x18\x02 \x03(\tR\vposterSizes\x12%\n" +
	"\x0ebackdrop_sizes\x18\x03 \x03(\tR\rbackdropSizes\x12\x1d\n" +
	"\n" +
	"logo_sizes\x18\x04 \x03(\tR\tlogoSizes\x12#\n" +
	"\rprofile_sizes\x18\x05 \x03(\tR\fprofileSizes\x12\x1f\n" +
	"\vstill_sizes\x18\x06 \x03(\tR\n" +
	"stillSizes\x12&\n" +
	"\x0fsecure_base_url\x18\a \x01(\tR\rsecureBaseUrl\"\xd6\x01\n" +
	"\x13ListTrendingRequest\x12E\n" +
	"\n" +
	"media_type\x18\x01 \x01(\x0e2&.muxcore.metadata.v1.TrendingMediaTypeR\tmediaType\x12H\n" +
	"\vtime_window\x18\x02 \x01(\x0e2'.muxcore.metadata.v1.TrendingTimeWindowR\n" +
	"timeWindow\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\"\xad\x01\n" +
	"\x14ListTrendingResponse\x12;\n" +
	"\aresults\x18\x01 \x03(\v2!.muxcore.metadata.v1.SearchResultR\aresults\x12#\n" +
	"\rtotal_results\x18\x02 \x01(\x05R\ftotalResults\x12\x1f\n" +
	"\vtotal_pages\x18\x03 \x01(\x05R\n" +
	"totalPages\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\"x\n" +
	"\x12ListPopularRequest\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.muxcore.metadata.v1.MediaTypeR\x04type\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\"\xac\x01\n" +
	"\x13ListPopularResponse\x12;\n" +
	"\aresults\x18\x01 \x03(\v2!.muxcore.metadata.v1.SearchResultR\aresults\x12#\n" +
	"\rtotal_results\x18\x02 \x01(\x05R\ftotalResults\x12\x1f\n" +
	"\vtotal_pages\x18\x03 \x01(\x05R\n" +
	"totalPages\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page*P\n" +
	"\tMediaType\x12\x1a\n" +
	"\x16MEDIA_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10MEDIA_TYPE_MOVIE\x10\x01\x12\x11\n" +
	"\rMEDIA_TYPE_TV\x10\x02*\x90\x01\n" +
	"\x11TrendingMediaType\x12#\n" +
	"\x1fTRENDING_MEDIA_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TRENDING_MEDIA_TYPE_ALL\x10\x01\x12\x1d\n" +
	"\x19TRENDING_MEDIA_TYPE_MOVIE\x10\x02\x12\x1a\n" +
	"\x16TRENDING_MEDIA_TYPE_TV\x10\x03*w\n" +
	"\x12TrendingTimeWindow\x12$\n" +
	" TRENDING_TIME_WINDOW_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18TRENDING_TIME_WINDOW_DAY\x10\x01\x12\x1d\n" +
	"\x19TRENDING_TIME_WINDOW_WEEK\x10\x022\xef\x04\n" +
	"\x0fMetadataService\x12Q\n" +
	"\x06Search\x12\".muxcore.metadata.v1.SearchRequest\x1a#.muxcore.metadata.v1.SearchResponse\x12l\n" +
	"\x0fGetMovieDetails\x12+.muxcore.metadata.v1.GetMovieDetailsRequest\x1a,.muxcore.metadata.v1.GetMovieDetailsResponse\x12c\n" +
	"\fGetTVDetails\x12(.muxcore.metadata.v1.GetTVDetailsRequest\x1a).muxcore.metadata.v1.GetTVDetailsResponse\x12o\n" +
	"\x10GetConfiguration\x12,.muxcore.metadata.v1.GetConfigurationRequest\x1a-.muxcore.metadata.v1.GetConfigurationResponse\x12c\n" +
	"\fListTrending\x12(.muxcore.metadata.v1.ListTrendingRequest\x1a).muxcore.metadata.v1.ListTrendingResponse\x12`\n" +
	"\vListPopular\x12'.muxcore.metadata.v1.ListPopularRequest\x1a(.muxcore.metadata.v1.ListPopularResponseBDZBgithub.com/Muxcore-Media/metadata-tmdb/proto/metadatav1;metadatav1b\x06proto3"

var (
	file_proto_metadatav1_metadata_proto_rawDescOnce sync.Once
	file_proto_metadatav1_metadata_proto_rawDescData []byte
)

func file_proto_metadatav1_metadata_proto_rawDescGZIP() []byte {
	file_proto_metadatav1_metadata_proto_rawDescOnce.Do(func() {
		file_proto_metadatav1_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_metadatav1_metadata_proto_rawDesc), len(file_proto_metadatav1_metadata_proto_rawDesc)))
	})
	return file_proto_metadatav1_metadata_proto_rawDescData
}

var file_proto_metadatav1_metadata_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_metadatav1_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_proto_metadatav1_metadata_proto_goTypes = []any{
	(MediaType)(0),                   // 0: muxcore.metadata.v1.MediaType
	(TrendingMediaType)(0),           // 1: muxcore.metadata.v1.TrendingMediaType
	(TrendingTimeWindow)(0),          // 2: muxcore.metadata.v1.TrendingTimeWindow
	(*SearchRequest)(nil),            // 3: muxcore.metadata.v1.SearchRequest
	(*SearchResponse)(nil),           // 4: muxcore.metadata.v1.SearchResponse
	(*SearchResult)(nil),             // 5: muxcore.metadata.v1.SearchResult
	(*GetMovieDetailsRequest)(nil),   // 6: muxcore.metadata.v1.GetMovieDetailsRequest
	(*GetMovieDetailsResponse)(nil),  // 7: muxcore.metadata.v1.GetMovieDetailsResponse
	(*Collection)(nil),               // 8: muxcore.metadata.v1.Collection
	(*Genre)(nil),                    // 9: muxcore.metadata.v1.Genre
	(*ProductionCompany)(nil),        // 10: muxcore.metadata.v1.ProductionCompany
	(*SpokenLanguage)(nil),           // 11: muxcore.metadata.v1.SpokenLanguage
	(*Video)(nil),                    // 12: muxcore.metadata.v1.Video
	(*Credits)(nil),                  // 13: muxcore.metadata.v1.Credits
	(*CastMember)(nil),               // 14: muxcore.metadata.v1.CastMember
	(*CrewMember)(nil),               // 15: muxcore.metadata.v1.CrewMember
	(*GetTVDetailsRequest)(nil),      // 16: muxcore.metadata.v1.GetTVDetailsRequest
	(*GetTVDetailsResponse)(nil),     // 17: muxcore.metadata.v1.GetTVDetailsResponse
	(*CreatedBy)(nil),                // 18: muxcore.metadata.v1.CreatedBy
	(*Network)(nil),                  // 19: muxcore.metadata.v1.Network
	(*Season)(nil),                   // 20: muxcore.metadata.v1.Season
	(*GetConfigurationRequest)(nil),  // 21: muxcore.metadata.v1.GetConfigurationRequest
	(*GetConfigurationResponse)(nil), // 22: muxcore.metadata.v1.GetConfigurationResponse
	(*ListTrendingRequest)(nil),      // 23: muxcore.metadata.v1.ListTrendingRequest
	(*ListTrendingResponse)(nil),     // 24: muxcore.metadata.v1.ListTrendingResponse
	(*ListPopularRequest)(nil),       // 25: muxcore.metadata.v1.ListPopularRequest
	(*ListPopularResponse)(nil),      // 26: muxcore.metadata.v1.ListPopularResponse
}
var file_proto_metadatav1_metadata_proto_depIdxs = []int32{
	0,  // 0: muxcore.metadata.v1.SearchRequest.type:type_name -> muxcore.metadata.v1.MediaType
	5,  // 1: muxcore.metadata.v1.SearchResponse.results:type_name -> muxcore.metadata.v1.SearchResult
	0,  // 2: muxcore.metadata.v1.SearchResult.media_type:type_name -> muxcore.metadata.v1.MediaType
	9,  // 3: muxcore.metadata.v1.GetMovieDetailsResponse.genres:type_name -> muxcore.metadata.v1.Genre
	10, // 4: muxcore.metadata.v1.GetMovieDetailsResponse.production_companies:type_name -> muxcore.metadata.v1.ProductionCompany
	11, // 5: muxcore.metadata.v1.GetMovieDetailsResponse.spoken_languages:type_name -> muxcore.metadata.v1.SpokenLanguage
	12, // 6: muxcore.metadata.v1.GetMovieDetailsResponse.videos:type_name -> muxcore.metadata.v1.Video
	13, // 7: muxcore.metadata.v1.GetMovieDetailsResponse.credits:type_name -> muxcore.metadata.v1.Credits
	8,  // 8: muxcore.metadata.v1.GetMovieDetailsResponse.belongs_to_collection:type_name -> muxcore.metadata.v1.Collection
	14, // 9: muxcore.metadata.v1.Credits.cast:type_name -> muxcore.metadata.v1.CastMember
	15, // 10: muxcore.metadata.v1.Credits.crew:type_name -> muxcore.metadata.v1.CrewMember
	9,  // 11: muxcore.metadata.v1.GetTVDetailsResponse.genres:type_name -> muxcore.metadata.v1.Genre
	20, // 12: muxcore.metadata.v1.GetTVDetailsResponse.seasons:type_name -> muxcore.metadata.v1.Season
	10, // 13: muxcore.metadata.v1.GetTVDetailsResponse.production_companies:type_name -> muxcore.metadata.v1.ProductionCompany
	11, // 14: muxcore.metadata.v1.GetTVDetailsResponse.spoken_languages:type_name -> muxcore.metadata.v1.SpokenLanguage
	12, // 15: muxcore.metadata.v1.GetTVDetailsResponse.videos:type_name -> muxcore.metadata.v1.Video
	13, // 16: muxcore.metadata.v1.GetTVDetailsResponse.credits:type_name -> muxcore.metadata.v1.Credits
	18, // 17: muxcore.metadata.v1.GetTVDetailsResponse.created_by:type_name -> muxcore.metadata.v1.CreatedBy
	19, // 18: muxcore.metadata.v1.GetTVDetailsResponse.networks:type_name -> muxcore.metadata.v1.Network
	1,  // 19: muxcore.metadata.v1.ListTrendingRequest.media_type:type_name -> muxcore.metadata.v1.TrendingMediaType
	2,  // 20: muxcore.metadata.v1.ListTrendingRequest.time_window:type_name -> muxcore.metadata.v1.TrendingTimeWindow
	5,  // 21: muxcore.metadata.v1.ListTrendingResponse.results:type_name -> muxcore.metadata.v1.SearchResult
	0,  // 22: muxcore.metadata.v1.ListPopularRequest.type:type_name -> muxcore.metadata.v1.MediaType
	5,  // 23: muxcore.metadata.v1.ListPopularResponse.results:type_name -> muxcore.metadata.v1.SearchResult
	3,  // 24: muxcore.metadata.v1.MetadataService.Search:input_type -> muxcore.metadata.v1.SearchRequest
	6,  // 25: muxcore.metadata.v1.MetadataService.GetMovieDetails:input_type -> muxcore.metadata.v1.GetMovieDetailsRequest
	16, // 26: muxcore.metadata.v1.MetadataService.GetTVDetails:input_type -> muxcore.metadata.v1.GetTVDetailsRequest
	21, // 27: muxcore.metadata.v1.MetadataService.GetConfiguration:input_type -> muxcore.metadata.v1.GetConfigurationRequest
	23, // 28: muxcore.metadata.v1.MetadataService.ListTrending:input_type -> muxcore.metadata.v1.ListTrendingRequest
	25, // 29: muxcore.metadata.v1.MetadataService.ListPopular:input_type -> muxcore.metadata.v1.ListPopularRequest
	4,  // 30: muxcore.metadata.v1.MetadataService.Search:output_type -> muxcore.metadata.v1.SearchResponse
	7,  // 31: muxcore.metadata.v1.MetadataService.GetMovieDetails:output_type -> muxcore.metadata.v1.GetMovieDetailsResponse
	17, // 32: muxcore.metadata.v1.MetadataService.GetTVDetails:output_type -> muxcore.metadata.v1.GetTVDetailsResponse
	22, // 33: muxcore.metadata.v1.MetadataService.GetConfiguration:output_type -> muxcore.metadata.v1.GetConfigurationResponse
	24, // 34: muxcore.metadata.v1.MetadataService.ListTrending:output_type -> muxcore.metadata.v1.ListTrendingResponse
	26, // 35: muxcore.metadata.v1.MetadataService.ListPopular:output_type -> muxcore.metadata.v1.ListPopularResponse
	30, // [30:36] is the sub-list for method output_type
	24, // [24:30] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_proto_metadatav1_metadata_proto_init() }
func file_proto_metadatav1_metadata_proto_init() {
	if File_proto_metadatav1_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_metadatav1_metadata_proto_rawDesc), len(file_proto_metadatav1_metadata_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_metadatav1_metadata_proto_goTypes,
		DependencyIndexes: file_proto_metadatav1_metadata_proto_depIdxs,
		EnumInfos:         file_proto_metadatav1_metadata_proto_enumTypes,
		MessageInfos:      file_proto_metadatav1_metadata_proto_msgTypes,
	}.Build()
	File_proto_metadatav1_metadata_proto = out.File
	file_proto_metadatav1_metadata_proto_goTypes = nil
	file_proto_metadatav1_metadata_proto_depIdxs = nil
}
